version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.4
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo Running build...

  post_build:
    commands:
      - echo Build complete.
      - echo Packaging and uploading artifacts (if applicable)...

artifacts:
  files:
    - '**/*' 
  discard-paths: no
  base-directory: build # Specify the output directory (e.g., `build` or `dist`)

cache:
  paths:
    - node_modules/**/* # Cache dependencies for faster builds
